"""Shared HTML rendering helpers."""

from collections import Counter
from datetime import datetime, timezone
import html

from tokencause.constants import __version__

HTML_BAR_CSS = """
    .bar-line { display: flex; justify-content: space-between; gap: 16px; align-items: baseline; }
    .bar-share { color: #334155; font-weight: 600; white-space: nowrap; }
    .bar-detail { color: #475569; }
    .bar-track { height: 8px; background: #e2e8f0; border-radius: 999px; margin-top: 7px; overflow: hidden; }
    .bar-fill { height: 100%; background: #2563eb; border-radius: inherit; }
"""

HTML_FOOTER_CSS = """
    footer { margin-top: 28px; color: #64748b; font-size: 12px; }
"""


def html_rows(rows: list[tuple[str, str]]) -> str:
    return "\n".join(
        f"<tr><td>{html.escape(left)}</td><td>{html.escape(right)}</td></tr>"
        for left, right in rows
    )


def html_footer() -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"<footer>Generated by TokenCause {html.escape(__version__)} at {html.escape(generated_at)}. Local-only report.</footer>"


def html_bar_rows(rows: list[tuple[str, int, int, str]]) -> str:
    rendered = []
    for label, tokens, total, detail in rows:
        share = tokens / (total or 1)
        percent = f"{share:.0%}"
        width = min(100, max(1 if tokens > 0 else 0, round(share * 100)))
        rendered.append(
            "<tr>"
            f"<td>{html.escape(label)}</td>"
            "<td>"
            '<div class="bar-line">'
            f'<span class="bar-detail">{html.escape(detail)}</span>'
            f'<span class="bar-share">{html.escape(percent)}</span>'
            "</div>"
            '<div class="bar-track">'
            f'<div class="bar-fill" style="width: {width}%;"></div>'
            "</div>"
            "</td>"
            "</tr>"
        )
    return "\n".join(rendered)


def html_table_rows(rows: list[list[str]]) -> str:
    return "\n".join(
        "<tr>" + "".join(f"<td>{html.escape(cell)}</td>" for cell in row) + "</tr>"
        for row in rows
    )


def overview_recommendations(driver_tokens: Counter[str]) -> list[str]:
    recommendations: list[str] = []
    for driver, _tokens in driver_tokens.most_common(5):
        if driver == "Long tool output":
            recommendations.append("Shorten test and command output before it enters the agent context; prefer focused commands, `tail`, or summarized logs.")
        elif driver == "Error/test log noise":
            recommendations.append("Shorten test and error logs, then dedupe repeated failures before rerunning the same command.")
        elif driver == "Cache-heavy context":
            recommendations.append("Compact or restart sessions when cache-read context dominates recent work.")
        elif driver == "Repeated context":
            recommendations.append("Split long sessions or summarize repeated chunks once they start recurring.")
        elif driver == "Repeated file/artifact context":
            recommendations.append("Summarize repeated files or inspect narrower sections instead of reloading full artifacts.")
        elif driver == "Expensive file context":
            recommendations.append("Ignore or summarize lockfiles, generated files, fixtures, schemas, snapshots, and minified assets.")
        elif driver == "Retry/failure loop":
            recommendations.append("Change strategy after repeated failures; avoid rerunning identical commands without new evidence.")
        elif driver == "Session drift":
            recommendations.append("Compact or start a fresh session when late turns become much larger than early turns.")
        elif driver == "Environment issue":
            recommendations.append("Resolve setup blockers outside the agent loop, then resume with a short error summary and one validation command.")
        elif driver == "Broad exploration":
            recommendations.append("Narrow broad workspace exploration to a subsystem, file range, or explicit hypothesis before continuing.")
    return list(dict.fromkeys(recommendations))[:5]
